#!/usr/bin/bash


# Import cargo packages 
source packages/cargo 

# Cargo installation  
if test ! $(which cargo); then
    curl https://sh.rustup.rs -sSf | sh
else
    echo "Cargo is already installed!"
fi

# Package installation
echo "Installing packages..."
cargo install ${PACKAGES[@]}
