#!/bin/bash

# Start simple X hotkey daemon
sxhkd &

# Screens 
laptop="eDP-1"
monitor1="DP-1-8"
monitor2="DP-1-1"

# Screen status
laptop_stat=$(xrandr -q | grep -w $laptop)
monitor1_stat=$(xrandr -q | grep -w $monitor1)
monitor2_stat=$(xrandr -q | grep -w $monitor2)

# Are they connected: `xrandr -q | grep -w connected`
if [[ $monitor1_stat = *connected* && $monitor2_stat = *connected* ]]; then
    xrandr --output $laptop --off
    xrandr --output $monitor2 --mode 2560x1440 --primary 
    xrandr --output $monitor1 --mode 2560x1440 --left-of $monitor2 
    bspc monitor $monitor2 -d I III V VII IX
    bspc monitor $monitor1 -d II IV VI VIII X
else
    bspc monitor $laptop -d I II III IV V VI VII VIII IX X
fi
bspc desktop I -f

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules

# bspc rule -a Inkscape   desktop=^4 state=tiled follow=on
bspc rule -a Firefox    state=tiled
bspc rule -a mplayer2   state=floating
bspc rule -a Sxiv       state=floating
bspc rule -a Zathura    state=tiled
bspc rule -a Kupfer.py  focus=on
bspc rule -a Screenkey  manage=off

# Set wallpaper
WDIR="/home/justin/.config/wall"
if [[ $monitor1_stat = *connected* && $monitor2_stat = *connected* ]]; then
    xwallpaper --output $monitor1 --trim 2560x1440+0+0 --focus $WDIR/dualbrain.jpg --output $monitor2 --trim 2560x1440+2560+0 --focus $WDIR/dualbrain.jpg
else
    xwallpaper --focus $WDIR/firewatch.jpg
fi

# $HOME/.config/polybar/launch.sh

# Source the colors.
# . "${HOME}/.cache/wal/colors.sh"
# bspc config normal_border_color "$color1"
# bspc config active_border_color "$color2"
# bspc config focused_border_color "$color15"
# bspc config presel_feedback_color "$color1"

# picom &
