#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules

bspc rule -a Inkscape   desktop=^4 state=tiled follow=on
bspc rule -a Firefox    state=tiled
bspc rule -a mplayer2   state=floating
bspc rule -a Sxiv       state=floating
bspc rule -a Zathura    state=tiled
bspc rule -a Kupfer.py  focus=on
bspc rule -a Screenkey  manage=off

feh --bg-fill $HOME/.config/wall/firewatch.jpg
$HOME/.config/polybar/launch.sh

# Source the colors.

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# picom &
